### ISSUE TITLE
Add float and double to possible data types to array-1.0/1

### ISSUE THREAD

**Issue by matze** [datastreaming/htypes#2]
I know you probably started that header description just with detectors in mind but in my opinion it is general enough to describe arbitrary array data (as the name actually implies). Hence, it would make perfect sense – and for our purposes it would be a requirement – to add `float` and `double` type specifiers to the list of integral types.

**Comment by simongregorebner** [comment]
actually also float16, float32 (float), float64 (double) are supported, they are just not documented, sorry
will update the docs ...

**Comment by simongregorebner** [comment]
Hope things are more clear now. Please reopen if you think stuff is still unclear...
